---
title: "Team 3 Project Proposal"
description: |
  This page contains the Project Proposal.
author:
  - name: Leslie Long Nu
    url: https://www.linkedin.com/in/leslielongnu/
  - name: Raunak Kapur
    url: https://www.linkedin.com/in/raunak-kapur-520b47141/
  - name: Raveena Chakrapani
    url: https://www.linkedin.com/in/raveena-chakrapani-444a60174/
date: "2022-05-27"
output: 
  distill::distill_article:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE)
```

# Motivation

In general, we have Several commercial software packages in market to draw data and their summaries. However,ideally, such tools should be open source, freely available and allow contributions or
modifications by users. Inspired by Prof Kam, with the acquired coding skills and understanding of data ,this group project aims to create such flexible website by making use of interactive visualizations to answer questions from [VAST Challenge 2022](https://vast-challenge.github.io/2022/) Challenge 3 to find out the Economic status of the City of Engagement, Ohio USA.
 

# Problem Statements 
Following are the questions we aim to answer, referencing from VAST Challenge 2022 Challenge 3 questions: 

***Challenge 3: Economic** considers the financial health of the city. Over time, are businesses growing or shrinking? How are people changing jobs? Are standards of living improving or declining over time?*

*Consider the financial status of Engagement’s businesses and residents, and use visual analytic techniques to address these questions.*

1. Over the period covered by the dataset, which businesses appear to be more prosperous? Which appear to be struggling? Describe your rationale for your answers. Limit your response to 10 images and 500 words.
2. How does the financial health of the residents change over the period covered by the dataset? How do wages compare to the overall cost of living in Engagement? Are there groups that appear to exhibit similar patterns? Describe your rationale for your answers. Limit your response to 10 images and 500 words.
3. Describe the health of the various employers within the city limits. What employment patterns do you observe? Do you notice any areas of particularly high or low turnover? Limit your response to 10 images and 500 words.

# Approach 
## Question 1
It is observed from the datasets provided by [VAST Challenge 2022](https://vast-challenge.github.io/2022/) that there are two types of businesses present in Engagement, Ohio USA, namely:

* Restaurants; 
* Pubs

They will be evaluated based on:

* Frequency and number of participants' visits;
* Revenue (participants' spending)

According to the dataset descriptions provided by VAST Challenge, all restaurants have a Prix Fixe food cost for participants to dine in and all pubs have a hourly cost to visit the pub. Therefore, assuming all visits to restaurants are for dinning, restaurants' revenue will be calculated by number of visits times Prix Fixe food cost. Similarly, pubs' revenue will be calculated by duration of visits times hourly cost of visits.  

Alternative approach of deriving balance difference before and after restaurants and pubs visits as spending is considered but not preferred as balance differences are inconsistent and could be due to unknown reasons.   

## Question 2

## Question 3

# Early Prototypes






